### ISSUE TITLE
Support for French release

### ISSUE THREAD

**Issue by maximilien-noal** [alekasm/SimCopterX#1]
Hello,

SimCopterX doesn't recognize it.

Here is the executable.

[SimCopter.zip](https://github.com/alekasm/SimCopterX/files/3294147/SimCopter.zip)

**Comment by alekasm** [comment]
Thank you for this, I haven't forgot about this French release. I'll be doing a code cleanup and adding support for more versions of SimCopter for Version 5. This is now next on my todo list :)

**Comment by alekasm** [comment]
Hey do you still have the link to where the executable is hosted?

**Comment by maximilien-noal** [comment]
I'll share a new link in a few hours. :)

**Comment by maximilien-noal** [comment]
Here it is (the full ISO) : https://drive.google.com/file/d/1eaeYfVeJk3qnxUv8F-8JaUXYteOojbAm/view?usp=sharing

**Comment by alekasm** [comment]
Edit: Found the original mirror. Hopefully I can get this updated soon.

**Comment by maximilien-noal** [comment]
Great ! Feel free to ask for more info. :)

I can also test the game on real hardware (using Windows 95 OSR 2).

**Comment by alekasm** [comment]
Hey so I tested both the iso you provided and the one provided on abandonware:
https://www.abandonware-france.org/ltf_abandon/ltf_jeu.php?id=1267&fic=liens&page=admin

Both seems to have a damaged iso and I can't mount it. I still have the original executable you linked me which appears to be "Version 1.1SC" or really, File Version 1.0.1.0.

Did the executable you give me come from the iso on abandonware-france?

![image](https://user-images.githubusercontent.com/45739284/63816308-af06f900-c905-11e9-9937-d2e97b53a387.png)


**Edit:** A temporary solution while I find this working iso is to use a supported executable (found on the simcopter.net site), patch it using SimCopterX, then start the game with command-line arguments like:

C:\CD\SimCopter\SimCopter.exe -lFrench

**Comment by maximilien-noal** [comment]
Yes, it's the same ISO.

Windows 10 doesn't support a lot of ISO files, even if they are correct.

PCem, DOSBox, VMWARE Player, and Daemon Tools do mount it.

I'll try to provide an alternate ISO shortly.

Thank you for your efforts !

**Comment by maximilien-noal** [comment]
Here's an ISO :
https://drive.google.com/file/d/1_3IxMurpWoAXdRx8s5H_qRnb_2-GXpYo/view?usp=sharing

**Comment by alekasm** [comment]
Released in Version 7, updating the website soon. Thank you for your extreme patience. By the way the French voices are awesome!
